from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier


# ============================================================
# CONFIGURATION
# ============================================================

DATA_DIR = Path("data")
MODEL_DIR = Path("models")

INCIDENT_FILE = DATA_DIR / "incidents.csv"
TRAFFIC_FILE = DATA_DIR / "traffic.csv"
WEATHER_FILE = DATA_DIR / "weather.csv"

MODEL_FILE = MODEL_DIR / "risk_model.pkl"


# ============================================================
# CHECK REAL DATA
# ============================================================

def require_real_file(path: Path):

    if not path.exists():
        raise FileNotFoundError(
            f"""
REAL DATA REQUIRED:

{path}

Put the actual government/source dataset here.
No synthetic/demo data is generated by this program.
"""
        )

    if path.stat().st_size == 0:
        raise ValueError(
            f"{path} is empty. Real data is required."
        )


require_real_file(INCIDENT_FILE)
require_real_file(TRAFFIC_FILE)
require_real_file(WEATHER_FILE)


# ============================================================
# LOAD DATA
# ============================================================

incidents = pd.read_csv(INCIDENT_FILE)
traffic = pd.read_csv(TRAFFIC_FILE)
weather = pd.read_csv(WEATHER_FILE)


# ============================================================
# REQUIRED COLUMNS
# ============================================================

required_incident_columns = {
    "incident_id",
    "segment_id",
    "timestamp",
    "incident_type",
    "severity",
}

required_traffic_columns = {
    "segment_id",
    "timestamp",
    "vehicle_count",
    "average_speed",
    "occupancy",
}

required_weather_columns = {
    "timestamp",
    "latitude",
    "longitude",
    "rainfall",
    "temperature",
    "visibility",
}


def check_columns(df, required, name):

    missing = required - set(df.columns)

    if missing:
        raise ValueError(
            f"{name} is missing columns: {sorted(missing)}"
        )


check_columns(
    incidents,
    required_incident_columns,
    "incidents.csv"
)

check_columns(
    traffic,
    required_traffic_columns,
    "traffic.csv"
)

check_columns(
    weather,
    required_weather_columns,
    "weather.csv"
)


# ============================================================
# CONVERT TIMESTAMPS
# ============================================================

incidents["timestamp"] = pd.to_datetime(
    incidents["timestamp"],
    errors="coerce"
)

traffic["timestamp"] = pd.to_datetime(
    traffic["timestamp"],
    errors="coerce"
)

weather["timestamp"] = pd.to_datetime(
    weather["timestamp"],
    errors="coerce"
)


# ============================================================
# REMOVE INVALID RECORDS
# ============================================================

incidents = incidents.dropna(
    subset=["segment_id", "timestamp"]
)

traffic = traffic.dropna(
    subset=[
        "segment_id",
        "timestamp",
        "average_speed",
        "occupancy",
    ]
)

weather = weather.dropna(
    subset=["timestamp"]
)


# ============================================================
# SORT
# ============================================================

traffic = traffic.sort_values(
    ["segment_id", "timestamp"]
)

incidents = incidents.sort_values(
    ["segment_id", "timestamp"]
)

weather = weather.sort_values(
    "timestamp"
)


# ============================================================
# CREATE TIME FEATURES
# ============================================================

traffic["hour"] = traffic["timestamp"].dt.hour

traffic["day_of_week"] = (
    traffic["timestamp"].dt.dayofweek
)

traffic["is_weekend"] = (
    traffic["day_of_week"] >= 5
).astype(int)


# ============================================================
# CONGESTION FEATURES
# ============================================================

# Historical average speed for each segment.
traffic["historical_avg_speed"] = (
    traffic
    .groupby("segment_id")["average_speed"]
    .transform(
        lambda x:
        x.shift(1)
        .rolling(
            window=24,
            min_periods=3
        )
        .mean()
    )
)


# Historical occupancy.
traffic["historical_avg_occupancy"] = (
    traffic
    .groupby("segment_id")["occupancy"]
    .transform(
        lambda x:
        x.shift(1)
        .rolling(
            window=24,
            min_periods=3
        )
        .mean()
    )
)


# Speed reduction compared with historical conditions.
traffic["speed_reduction"] = (
    (
        traffic["historical_avg_speed"]
        - traffic["average_speed"]
    )
    /
    traffic["historical_avg_speed"]
)


# ============================================================
# INCIDENT HISTORY
# ============================================================

# Count incidents per segment/time bucket.

incident_counts = (
    incidents
    .groupby(
        [
            "segment_id",
            pd.Grouper(
                key="timestamp",
                freq="h"
            )
        ]
    )
    .size()
    .reset_index(
        name="incident_count"
    )
)


# ============================================================
# MERGE INCIDENT HISTORY WITH TRAFFIC
# ============================================================

traffic = pd.merge_asof(
    traffic.sort_values("timestamp"),
    incident_counts.sort_values("timestamp"),
    on="timestamp",
    by="segment_id",
    direction="backward",
    tolerance=pd.Timedelta("1h"),
)


traffic["incident_count"] = (
    traffic["incident_count"]
    .fillna(0)
)


# ============================================================
# HISTORICAL INCIDENT FREQUENCY
# ============================================================

traffic["historical_incidents"] = (
    traffic
    .groupby("segment_id")["incident_count"]
    .transform(
        lambda x:
        x.shift(1)
        .rolling(
            window=24 * 7,
            min_periods=3
        )
        .sum()
    )
)


# ============================================================
# WEATHER JOIN
# ============================================================

# Weather must be mapped to the traffic observation
# using the actual timestamp/location relationship.

traffic = pd.merge_asof(
    traffic.sort_values("timestamp"),
    weather.sort_values("timestamp"),
    on="timestamp",
    direction="nearest",
    tolerance=pd.Timedelta("1h"),
)


# ============================================================
# TARGET
# ============================================================

# Predict whether an incident occurs in the NEXT hour.

future_incidents = (
    incident_counts.copy()
)

future_incidents["target_timestamp"] = (
    future_incidents["timestamp"]
    - pd.Timedelta(hours=1)
)


traffic = pd.merge(
    traffic,
    future_incidents[
        [
            "segment_id",
            "target_timestamp",
            "incident_count",
        ]
    ],
    left_on=[
        "segment_id",
        "timestamp",
    ],
    right_on=[
        "segment_id",
        "target_timestamp",
    ],
    how="left",
    suffixes=("", "_future")
)


traffic["incident_count_future"] = (
    traffic["incident_count_future"]
    .fillna(0)
)


traffic["risk_target"] = (
    traffic["incident_count_future"] > 0
).astype(int)


# ============================================================
# FEATURE SET
# ============================================================

FEATURES = [
    "average_speed",
    "occupancy",
    "historical_avg_speed",
    "historical_avg_occupancy",
    "speed_reduction",
    "historical_incidents",
    "rainfall",
    "temperature",
    "visibility",
    "hour",
    "day_of_week",
    "is_weekend",
]


# ============================================================
# CLEAN TRAINING DATA
# ============================================================

training_data = traffic.dropna(
    subset=FEATURES + ["risk_target"]
)


if len(training_data) < 100:
    raise ValueError(
        f"""
Only {len(training_data)} usable real observations found.

At least 100 observations are required by this
training script as a basic sanity check.

Obtain more real historical data.
No synthetic data will be generated.
"""
    )


X = training_data[FEATURES]

y = training_data["risk_target"]


# ============================================================
# CHECK TARGET
# ============================================================

if y.nunique() < 2:

    raise ValueError(
        """
The real dataset contains only one target class.

The model needs observations both WITH and WITHOUT
incidents.

Obtain more historical data.
"""
    )


# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y,
)


# ============================================================
# MODEL
# ============================================================

model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    random_state=42,
)


model.fit(
    X_train,
    y_train,
)


# ============================================================
# EVALUATION
# ============================================================

predictions = model.predict(X_test)

probabilities = model.predict_proba(X_test)[:, 1]


print(
    classification_report(
        y_test,
        predictions
    )
)


if y_test.nunique() == 2:

    print(
        "ROC-AUC:",
        roc_auc_score(
            y_test,
            probabilities
        )
    )


# ============================================================
# SAVE MODEL
# ============================================================

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


joblib.dump(
    {
        "model": model,
        "features": FEATURES,
    },
    MODEL_FILE,
)


print(
    f"Model saved to {MODEL_FILE}"
)