import logging
from datetime import datetime, timedelta
from sqlalchemy import select
from app.db.base import Base
from app.db.session import engine, AsyncSessionLocal
from app.models.domain import (
    LocationModel,
    OfficerModel,
    IncidentModel,
    DeploymentModel,
    ScheduleModel,
)

logger = logging.getLogger("nagpur_traffic.init_db")

SEED_LOCATIONS = [
    {
        "id": "LOC_VARIETY",
        "name": "Variety Square",
        "short_name": "Variety Sq.",
        "area": "Sitabuldi",
        "corridor": "Wardha Rd / Amravati Rd Link",
        "lat": 21.1466, "lng": 79.0831,
        "map_x": 220, "map_y": 185,
        "risk_score": 82.0,
        "risk_level": "High",
        "officers_assigned": 2,
        "recommended_officers": 4,
        "active_incidents": 2,
        "traffic_condition": "Severely Congested",
        "risk_factors": ["High vehicle volume", "Peak hour overlap", "Active accident nearby", "Signal malfunction reported"],
        "avg_speed_kmh": 14.0,
        "volume_pcu_hr": 4100.0,
        "queue_length_m": 62.0,
    },
    {
        "id": "LOC_RBI",
        "name": "RBI Square (Samvidhan Chowk)",
        "short_name": "RBI Square",
        "area": "Civil Lines",
        "corridor": "Central Ave / Wardha Rd North",
        "lat": 21.1525, "lng": 79.0864,
        "map_x": 235, "map_y": 165,
        "risk_score": 54.0,
        "risk_level": "Medium",
        "officers_assigned": 2,
        "recommended_officers": 2,
        "active_incidents": 1,
        "traffic_condition": "Moderate",
        "risk_factors": ["Government office proximity", "Lunch-hour pedestrian surge"],
        "avg_speed_kmh": 28.0,
        "volume_pcu_hr": 3200.0,
        "queue_length_m": 28.0,
    },
    {
        "id": "LOC_LAW_COLLEGE",
        "name": "Law College Square",
        "short_name": "Law College",
        "area": "Dharampeth",
        "corridor": "Amravati Rd / WHC Rd",
        "lat": 21.1528, "lng": 79.0620,
        "map_x": 145, "map_y": 158,
        "risk_score": 33.0,
        "risk_level": "Low",
        "officers_assigned": 1,
        "recommended_officers": 1,
        "active_incidents": 0,
        "traffic_condition": "Normal",
        "risk_factors": ["College dispersal at 17:00"],
        "avg_speed_kmh": 38.0,
        "volume_pcu_hr": 2100.0,
        "queue_length_m": 12.0,
    },
    {
        "id": "LOC_SHANKAR_NAGAR",
        "name": "Shankar Nagar Square",
        "short_name": "Shankar Nagar",
        "area": "Dharampeth",
        "corridor": "WHC Road",
        "lat": 21.1396, "lng": 79.0625,
        "map_x": 148, "map_y": 210,
        "risk_score": 28.0,
        "risk_level": "Low",
        "officers_assigned": 0,
        "recommended_officers": 1,
        "active_incidents": 0,
        "traffic_condition": "Free Flow",
        "risk_factors": ["Residential school zone"],
        "avg_speed_kmh": 44.0,
        "volume_pcu_hr": 1800.0,
        "queue_length_m": 8.0,
    },
    {
        "id": "LOC_CHHATRAPATI",
        "name": "Chhatrapati Square",
        "short_name": "Chhatrapati Sq.",
        "area": "Pratap Nagar",
        "corridor": "Wardha Rd / Ring Road",
        "lat": 21.1105, "lng": 79.0690,
        "map_x": 175, "map_y": 295,
        "risk_score": 88.0,
        "risk_level": "High",
        "officers_assigned": 0,
        "recommended_officers": 3,
        "active_incidents": 1,
        "traffic_condition": "Severely Congested",
        "risk_factors": ["No officer coverage", "Ring Road junction", "Heavy goods vehicle influx", "Historic accident hotspot"],
        "avg_speed_kmh": 11.0,
        "volume_pcu_hr": 4500.0,
        "queue_length_m": 75.0,
    },
    {
        "id": "LOC_RAHATE",
        "name": "Rahate Colony Square",
        "short_name": "Rahate Colony",
        "area": "Dhantoli",
        "corridor": "Wardha Rd Arterial",
        "lat": 21.1270, "lng": 79.0760,
        "map_x": 192, "map_y": 252,
        "risk_score": 71.0,
        "risk_level": "High",
        "officers_assigned": 1,
        "recommended_officers": 3,
        "active_incidents": 1,
        "traffic_condition": "Congested",
        "risk_factors": ["Market area", "Narrow approach roads", "Pedestrian conflict"],
        "avg_speed_kmh": 19.0,
        "volume_pcu_hr": 3700.0,
        "queue_length_m": 52.0,
    },
    {
        "id": "LOC_AJNI",
        "name": "Ajni Square",
        "short_name": "Ajni Sq.",
        "area": "Ajni",
        "corridor": "Wardha Rd Arterial",
        "lat": 21.1180, "lng": 79.0790,
        "map_x": 200, "map_y": 275,
        "risk_score": 58.0,
        "risk_level": "Medium",
        "officers_assigned": 2,
        "recommended_officers": 2,
        "active_incidents": 0,
        "traffic_condition": "Moderate",
        "risk_factors": ["Railway crossing proximity", "Goods traffic"],
        "avg_speed_kmh": 26.0,
        "volume_pcu_hr": 3100.0,
        "queue_length_m": 30.0,
    },
    {
        "id": "LOC_MEDICAL",
        "name": "Medical Square",
        "short_name": "Medical Sq.",
        "area": "Medical College Area",
        "corridor": "Great Nag Rd / Umred Rd Link",
        "lat": 21.1340, "lng": 79.0970,
        "map_x": 278, "map_y": 222,
        "risk_score": 62.0,
        "risk_level": "Medium",
        "officers_assigned": 1,
        "recommended_officers": 2,
        "active_incidents": 1,
        "traffic_condition": "Moderate-Congested",
        "risk_factors": ["Hospital traffic 24x7", "Emergency vehicle clearance needed"],
        "avg_speed_kmh": 22.0,
        "volume_pcu_hr": 2900.0,
        "queue_length_m": 35.0,
    },
    {
        "id": "LOC_TEL_EXCHANGE",
        "name": "Telephone Exchange Square",
        "short_name": "Tel. Exchange",
        "area": "Gandhibagh / CA Road",
        "corridor": "Central Avenue (CA Road)",
        "lat": 21.1490, "lng": 79.1170,
        "map_x": 322, "map_y": 188,
        "risk_score": 78.0,
        "risk_level": "High",
        "officers_assigned": 1,
        "recommended_officers": 3,
        "active_incidents": 1,
        "traffic_condition": "Congested",
        "risk_factors": ["Commercial zone", "Narrow roads", "Illegal parking"],
        "avg_speed_kmh": 16.0,
        "volume_pcu_hr": 3800.0,
        "queue_length_m": 55.0,
    },
    {
        "id": "LOC_AUTOMOTIVE",
        "name": "Automotive Square",
        "short_name": "Automotive Sq.",
        "area": "Kamptee Road",
        "corridor": "NH-44 North corridor",
        "lat": 21.1980, "lng": 79.1020,
        "map_x": 290, "map_y": 112,
        "risk_score": 29.0,
        "risk_level": "Low",
        "officers_assigned": 1,
        "recommended_officers": 1,
        "active_incidents": 0,
        "traffic_condition": "Normal",
        "risk_factors": ["Truck movement in early hours"],
        "avg_speed_kmh": 45.0,
        "volume_pcu_hr": 1900.0,
        "queue_length_m": 9.0,
    },
    {
        "id": "LOC_DHARAMPETH",
        "name": "Dharampeth Square",
        "short_name": "Dharampeth",
        "area": "Dharampeth",
        "corridor": "Amravati Road",
        "lat": 21.1560, "lng": 79.0530,
        "map_x": 118, "map_y": 148,
        "risk_score": 45.0,
        "risk_level": "Medium",
        "officers_assigned": 1,
        "recommended_officers": 1,
        "active_incidents": 0,
        "traffic_condition": "Moderate",
        "risk_factors": ["School zone peak hours"],
        "avg_speed_kmh": 32.0,
        "volume_pcu_hr": 2400.0,
        "queue_length_m": 18.0,
    },
    {
        "id": "LOC_ITWARI",
        "name": "Itwari Railway Station",
        "short_name": "Itwari",
        "area": "Itwari",
        "corridor": "CA Road / Station Area",
        "lat": 21.1462, "lng": 79.1005,
        "map_x": 282, "map_y": 195,
        "risk_score": 74.0,
        "risk_level": "High",
        "officers_assigned": 0,
        "recommended_officers": 3,
        "active_incidents": 1,
        "traffic_condition": "Congested",
        "risk_factors": ["No coverage", "Train arrival crowd", "Auto/rickshaw surge", "Station gate bottleneck"],
        "avg_speed_kmh": 12.0,
        "volume_pcu_hr": 3500.0,
        "queue_length_m": 60.0,
    },
    {
        "id": "LOC_AIRPORT",
        "name": "Airport Road Junction",
        "short_name": "Airport Jn.",
        "area": "Wardha Road",
        "corridor": "Wardha Rd South",
        "lat": 21.0920, "lng": 79.0490,
        "map_x": 142, "map_y": 335,
        "risk_score": 41.0,
        "risk_level": "Medium",
        "officers_assigned": 1,
        "recommended_officers": 1,
        "active_incidents": 0,
        "traffic_condition": "Normal-Moderate",
        "risk_factors": ["Flight schedule peaks", "NH-7 merge"],
        "avg_speed_kmh": 36.0,
        "volume_pcu_hr": 2200.0,
        "queue_length_m": 20.0,
    },
    {
        "id": "LOC_GANDHIBAGH",
        "name": "Gandhibagh Square",
        "short_name": "Gandhibagh",
        "area": "Gandhibagh",
        "corridor": "CA Road / Mahal",
        "lat": 21.1502, "lng": 79.0932,
        "map_x": 258, "map_y": 185,
        "risk_score": 66.0,
        "risk_level": "Medium",
        "officers_assigned": 2,
        "recommended_officers": 2,
        "active_incidents": 0,
        "traffic_condition": "Moderate",
        "risk_factors": ["Dense commercial area", "On-street market"],
        "avg_speed_kmh": 20.0,
        "volume_pcu_hr": 3000.0,
        "queue_length_m": 38.0,
    },
    {
        "id": "LOC_NAGPUR_CENTRAL",
        "name": "Nagpur Central (Zero Mile)",
        "short_name": "Zero Mile",
        "area": "Central Nagpur",
        "corridor": "Central Avenue",
        "lat": 21.1458, "lng": 79.0882,
        "map_x": 242, "map_y": 195,
        "risk_score": 51.0,
        "risk_level": "Medium",
        "officers_assigned": 3,
        "recommended_officers": 3,
        "active_incidents": 0,
        "traffic_condition": "Moderate",
        "risk_factors": ["Administrative hub", "VIP movement corridor"],
        "avg_speed_kmh": 29.0,
        "volume_pcu_hr": 2700.0,
        "queue_length_m": 24.0,
    },
]

SEED_OFFICERS = [
    { "id": "OFF_001", "badge_no": "NTP-2847", "name": "Rajesh Kumar Sharma", "rank": "Sub-Inspector", "zone": "Zone A - Sitabuldi", "location_id": "LOC_VARIETY", "location_name": "Variety Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 85.0, "phone": "9876543210" },
    { "id": "OFF_002", "badge_no": "NTP-3124", "name": "Sunita Prasad", "rank": "ASI", "zone": "Zone A - Sitabuldi", "location_id": "LOC_VARIETY", "location_name": "Variety Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 80.0, "phone": "9876543211" },
    { "id": "OFF_003", "badge_no": "NTP-1892", "name": "Manoj Patil", "rank": "Head Constable", "zone": "Zone B - Civil Lines", "location_id": "LOC_RBI", "location_name": "RBI Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 5.0, "workload_pct": 60.0, "phone": "9876543212" },
    { "id": "OFF_004", "badge_no": "NTP-2231", "name": "Priya Deshmukh", "rank": "Constable", "zone": "Zone B - Civil Lines", "location_id": "LOC_RBI", "location_name": "RBI Square", "availability": "On Duty", "shift": "14:00–22:00", "hours_on_duty": 2.0, "workload_pct": 45.0, "phone": "9876543213" },
    { "id": "OFF_005", "badge_no": "NTP-3455", "name": "Vikram Singh", "rank": "ASI", "zone": "Zone C - Dharampeth", "location_id": "LOC_LAW_COLLEGE", "location_name": "Law College Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 7.0, "workload_pct": 55.0, "phone": "9876543214" },
    { "id": "OFF_006", "badge_no": "NTP-1567", "name": "Anita Borse", "rank": "Constable", "zone": "Zone C - Dharampeth", "location_id": "LOC_DHARAMPETH", "location_name": "Dharampeth Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 50.0, "phone": "9876543215" },
    { "id": "OFF_007", "badge_no": "NTP-2788", "name": "Rahul Meshram", "rank": "Constable", "zone": "Zone D - Dhantoli", "location_id": "LOC_RAHATE", "location_name": "Rahate Colony Square", "availability": "On Duty", "shift": "14:00–22:00", "hours_on_duty": 3.0, "workload_pct": 72.0, "phone": "9876543216" },
    { "id": "OFF_008", "badge_no": "NTP-3001", "name": "Suresh Wankhede", "rank": "Head Constable", "zone": "Zone D - Dhantoli", "location_id": None, "location_name": None, "availability": "Available", "shift": "06:00–14:00", "hours_on_duty": 0.0, "workload_pct": 0.0, "phone": "9876543217" },
    { "id": "OFF_009", "badge_no": "NTP-2110", "name": "Deepa Nagrale", "rank": "ASI", "zone": "Zone E - Gandhibagh", "location_id": "LOC_GANDHIBAGH", "location_name": "Gandhibagh Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 65.0, "phone": "9876543218" },
    { "id": "OFF_010", "badge_no": "NTP-1745", "name": "Arun Rathod", "rank": "Constable", "zone": "Zone E - Gandhibagh", "location_id": "LOC_GANDHIBAGH", "location_name": "Gandhibagh Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 62.0, "phone": "9876543219" },
    { "id": "OFF_011", "badge_no": "NTP-3312", "name": "Kavita Shende", "rank": "Constable", "zone": "Zone F - Ajni", "location_id": "LOC_AJNI", "location_name": "Ajni Square", "availability": "On Duty", "shift": "14:00–22:00", "hours_on_duty": 4.0, "workload_pct": 58.0, "phone": "9876543220" },
    { "id": "OFF_012", "badge_no": "NTP-2043", "name": "Dinesh Kale", "rank": "Head Constable", "zone": "Zone F - Ajni", "location_id": "LOC_AJNI", "location_name": "Ajni Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 7.0, "workload_pct": 68.0, "phone": "9876543221" },
    { "id": "OFF_013", "badge_no": "NTP-1234", "name": "Pranav Joshi", "rank": "Sub-Inspector", "zone": "Zone G - CA Road", "location_id": "LOC_TEL_EXCHANGE", "location_name": "Tel. Exchange Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 5.0, "workload_pct": 78.0, "phone": "9876543222" },
    { "id": "OFF_014", "badge_no": "NTP-2556", "name": "Meena Kulkarni", "rank": "Constable", "zone": "Zone A - Sitabuldi", "location_id": None, "location_name": None, "availability": "Available", "shift": "14:00–22:00", "hours_on_duty": 0.0, "workload_pct": 0.0, "phone": "9876543223" },
    { "id": "OFF_015", "badge_no": "NTP-3089", "name": "Satish Bondre", "rank": "Constable", "zone": "Zone H - Kamptee Rd", "location_id": "LOC_AUTOMOTIVE", "location_name": "Automotive Square", "availability": "On Duty", "shift": "22:00–06:00", "hours_on_duty": 2.0, "workload_pct": 30.0, "phone": "9876543224" },
    { "id": "OFF_016", "badge_no": "NTP-1978", "name": "Laxmi Tirpude", "rank": "ASI", "zone": "Zone G - CA Road", "location_id": "LOC_MEDICAL", "location_name": "Medical Square", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 63.0, "phone": "9876543225" },
    { "id": "OFF_017", "badge_no": "NTP-2667", "name": "Harish Gajbhiye", "rank": "Constable", "zone": "Zone B - Civil Lines", "location_id": None, "location_name": None, "availability": "On Break", "shift": "06:00–14:00", "hours_on_duty": 5.0, "workload_pct": 70.0, "phone": "9876543226" },
    { "id": "OFF_018", "badge_no": "NTP-3200", "name": "Smita Mohod", "rank": "Constable", "zone": "Zone I - Wardha Rd South", "location_id": "LOC_AIRPORT", "location_name": "Airport Road Junction", "availability": "On Duty", "shift": "14:00–22:00", "hours_on_duty": 3.0, "workload_pct": 42.0, "phone": "9876543227" },
    { "id": "OFF_019", "badge_no": "NTP-1654", "name": "Bhushan Tembhare", "rank": "Head Constable", "zone": "Zone A - Sitabuldi", "location_id": "LOC_NAGPUR_CENTRAL", "location_name": "Zero Mile", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 7.0, "workload_pct": 52.0, "phone": "9876543228" },
    { "id": "OFF_020", "badge_no": "NTP-2899", "name": "Geeta Pawar", "rank": "Constable", "zone": "Zone A - Sitabuldi", "location_id": "LOC_NAGPUR_CENTRAL", "location_name": "Zero Mile", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 48.0, "phone": "9876543229" },
    { "id": "OFF_021", "badge_no": "NTP-3441", "name": "Ravi Chandrakar", "rank": "Constable", "zone": "Zone A - Sitabuldi", "location_id": "LOC_NAGPUR_CENTRAL", "location_name": "Zero Mile", "availability": "On Duty", "shift": "06:00–14:00", "hours_on_duty": 6.0, "workload_pct": 50.0, "phone": "9876543230" },
]

now = datetime.now()
def mins_ago(m: int) -> str:
    return (now - timedelta(minutes=m)).isoformat()

SEED_INCIDENTS = [
    { "id": "INC_001", "type": "Accident", "location_id": "LOC_VARIETY", "location_name": "Variety Square", "severity": "Severe", "short_description": "2-Vehicle Collision (Northbound)", "description": "Two-vehicle collision, partial road block, northbound lane affected. Ambulance on scene.", "reported_at": mins_ago(22), "status": "Responding", "officer_assigned": "NTP-2847", "estimated_clearance_min": 25 },
    { "id": "INC_002", "type": "Congestion", "location_id": "LOC_CHHATRAPATI", "location_name": "Chhatrapati Square", "severity": "Critical", "short_description": "Wardha Rd 300m Backup", "description": "Severe backup on Wardha Road southbound, spillback 300m. Heavy vehicles queued.", "reported_at": mins_ago(45), "status": "Active", "officer_assigned": None, "estimated_clearance_min": 40 },
    { "id": "INC_003", "type": "Signal Failure", "location_id": "LOC_VARIETY", "location_name": "Variety Square", "severity": "Moderate", "short_description": "Signal Controller Failure", "description": "Traffic signal controller malfunction, manual control required.", "reported_at": mins_ago(35), "status": "Active", "officer_assigned": "NTP-3124", "estimated_clearance_min": 60 },
    { "id": "INC_004", "type": "Congestion", "location_id": "LOC_TEL_EXCHANGE", "location_name": "Telephone Exchange Square", "severity": "Severe", "short_description": "Vendor Illegal Parking", "description": "Illegal parking by vendors blocking two lanes on CA Road.", "reported_at": mins_ago(18), "status": "Active", "officer_assigned": "NTP-1234", "estimated_clearance_min": 30 },
    { "id": "INC_005", "type": "Congestion", "location_id": "LOC_ITWARI", "location_name": "Itwari Railway Station", "severity": "Severe", "short_description": "Station Gate Chokepoint", "description": "Train arrival surge, auto/rickshaws blocking station gate approach.", "reported_at": mins_ago(12), "status": "Active", "officer_assigned": None, "estimated_clearance_min": 35 },
    { "id": "INC_006", "type": "Crowd", "location_id": "LOC_MEDICAL", "location_name": "Medical Square", "severity": "Moderate", "short_description": "GMCH Gathering on Road", "description": "Large gathering outside GMCH, pedestrians spilling onto road.", "reported_at": mins_ago(55), "status": "Responding", "officer_assigned": "NTP-1978", "estimated_clearance_min": 20 },
    { "id": "INC_007", "type": "Congestion", "location_id": "LOC_RAHATE", "location_name": "Rahate Colony Square", "severity": "Moderate", "short_description": "Market Day Bottleneck", "description": "Market day pedestrian and auto congestion, reduced road width.", "reported_at": mins_ago(70), "status": "Monitoring", "officer_assigned": "NTP-2788", "estimated_clearance_min": 45 },
    { "id": "INC_008", "type": "Road Work", "location_id": "LOC_RBI", "location_name": "RBI Square", "severity": "Minor", "short_description": "NMC Utility Work (1-Lane)", "description": "NMC utility repair works – one lane closed eastbound.", "reported_at": mins_ago(180), "status": "Monitoring", "officer_assigned": "NTP-1892", "estimated_clearance_min": 120 },
    { "id": "INC_009", "type": "Accident", "location_id": "LOC_AJNI", "location_name": "Ajni Square", "severity": "Minor", "short_description": "Minor Rear-End Collision", "description": "Minor rear-end collision, vehicles moved to side. No injury.", "reported_at": mins_ago(95), "status": "Resolved", "officer_assigned": "NTP-2043", "estimated_clearance_min": None },
    { "id": "INC_010", "type": "Blockage", "location_id": "LOC_SHANKAR_NAGAR", "location_name": "Shankar Nagar Square", "severity": "Minor", "short_description": "Stalled Truck on Left Lane", "description": "Broken-down truck on left lane. Recovery vehicle dispatched.", "reported_at": mins_ago(140), "status": "Resolved", "officer_assigned": None, "estimated_clearance_min": None },
]

SEED_DEPLOYMENTS = [
    {
        "id": "DEP_001",
        "officer_id": "OFF_008",
        "officer_name": "Suresh Wankhede",
        "officer_badge": "NTP-3001",
        "from_location_id": None,
        "from_location_name": "Reserve (Unassigned)",
        "to_location_id": "LOC_CHHATRAPATI",
        "to_location_name": "Chhatrapati Square",
        "priority": "Critical",
        "eta_minutes": 8,
        "reason": "Zero officer coverage at High-risk location with active congestion incident.",
        "status": "Pending",
        "is_ai": True,
    },
    {
        "id": "DEP_002",
        "officer_id": "OFF_014",
        "officer_name": "Meena Kulkarni",
        "officer_badge": "NTP-2556",
        "from_location_id": None,
        "from_location_name": "Reserve (Unassigned)",
        "to_location_id": "LOC_ITWARI",
        "to_location_name": "Itwari Railway Station",
        "priority": "Critical",
        "eta_minutes": 11,
        "reason": "No officer coverage at Itwari Station during peak train arrival. Active crowd incident.",
        "status": "Pending",
        "is_ai": True,
    },
    {
        "id": "DEP_003",
        "officer_id": "OFF_017",
        "officer_name": "Harish Gajbhiye",
        "officer_badge": "NTP-2667",
        "from_location_id": None,
        "from_location_name": "Break (Zone B)",
        "to_location_id": "LOC_VARIETY",
        "to_location_name": "Variety Square",
        "priority": "High",
        "eta_minutes": 6,
        "reason": "Accident scene at Variety Square requires additional officer for traffic management.",
        "status": "Pending",
        "is_ai": True,
    },
    {
        "id": "DEP_004",
        "officer_id": "OFF_004",
        "officer_name": "Priya Deshmukh",
        "officer_badge": "NTP-2231",
        "from_location_id": "LOC_RBI",
        "from_location_name": "RBI Square",
        "to_location_id": "LOC_TEL_EXCHANGE",
        "to_location_name": "Telephone Exchange Square",
        "priority": "High",
        "eta_minutes": 9,
        "reason": "RBI Square risk is Medium and currently over-covered. Telephone Exchange has High risk with illegal parking incident.",
        "status": "Pending",
        "is_ai": True,
    },
    {
        "id": "DEP_005",
        "officer_id": "OFF_005",
        "officer_name": "Vikram Singh",
        "officer_badge": "NTP-3455",
        "from_location_id": "LOC_LAW_COLLEGE",
        "from_location_name": "Law College Square",
        "to_location_id": "LOC_RAHATE",
        "to_location_name": "Rahate Colony Square",
        "priority": "Medium",
        "eta_minutes": 14,
        "reason": "Law College is Low-risk and adequately staffed. Rahate Colony needs additional coverage.",
        "status": "Pending",
        "is_ai": True,
    },
]

async def init_database():
    """Create tables and seed initial Nagpur data if empty."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        # Check if locations exist
        result = await session.execute(select(LocationModel).limit(1))
        if result.scalar_one_or_none() is None:
            logger.info("Seeding initial Nagpur locations...")
            for loc_data in SEED_LOCATIONS:
                session.add(LocationModel(**loc_data))

            for off_data in SEED_OFFICERS:
                session.add(OfficerModel(**off_data))

            for inc_data in SEED_INCIDENTS:
                session.add(IncidentModel(**inc_data))

            for dep_data in SEED_DEPLOYMENTS:
                session.add(DeploymentModel(**dep_data))

            # Initial sample schedules
            for i, off in enumerate(SEED_OFFICERS):
                session.add(
                    ScheduleModel(
                        id=f"SCH_{i+1:03d}",
                        officer_id=off["id"],
                        officer_name=off["name"],
                        shift_date=datetime.now().strftime("%Y-%m-%d"),
                        shift_time=off["shift"],
                        zone=off["zone"],
                        assigned_location_id=off.get("location_id"),
                        status="Scheduled"
                    )
                )

            await session.commit()
            logger.info("Database seeding completed successfully.")
        else:
            logger.info("Database already contains data, skipping seed.")
